# Generated by Django 2.2.19 on 2022-05-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220522_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='autor',
            new_name='author',
        ),
    ]
