# Generated by Django 2.2.19 on 2022-06-17 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220613_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator('1, слишком малое значение')], verbose_name='время приготовления'),
        ),
    ]
