# Generated by Django 2.2.19 on 2022-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220605_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='введите email', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
